title: KD Shares
remote_theme: "verinvest-pl/WhatATheme"
heroimage: /assets/img/hero.jpg
description: Investing in Fintech Innovation for a Brighter Financial Future.

about: KD Shares ASI sp. z o.o. jest wewnętrznie zarządzaną alternatywną spółką inwestycyjną utworzoną na podstawie ustawy o funduszach inwestycyjnych i zarządzaniu alternatywnymi funduszami inwestycyjnymi. Spółka wpisana jest do rejestru zarządzających alternatywnymi spółkami inwestycyjnymi prowadzonego przez Komisję Nadzoru Finansowego pod numerem PLZASI00360.

authors:
  - image: https://static.wixstatic.com/media/d04b51_76a14f9c5a04430db294d81abb5a7c56~mv2.jpg/v1/fill/w_392,h_550,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/Krzysztof%20Drzyzga.jpg
    name: Krzysztof Drzyzga
    about: 'Krzysztof Drzyzga - Ponad 20 lat doświadczenia: w branży finansowej, płatności zdalne i zbliżeniowe, programy lojalnościowe, zarządzanie produktami, wspieranie rozwoju branży fintech, startupów i zarządzanie produktami. Odpowiedzialny za ogólną strategię i rozwój Verestro.'
  - image: /assets/img/kasia.jpg
    name: Katarzyna Drzyzga
    about: 'Katarzyna Drzyzga - Z branżą płatniczą i fintech związana od 15 lat. Odpowiedzialna za dział HR w Verestro. '

address: '<b>KD Shares ASI spółka z ograniczoną odpowiedzialnością</b>, ul.Promienna 10, 03-672 Warszawa <p>Spółka wpisana jest do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejestrowy dla m.st. Warszawy w Warszawie, XIV Wydział Gospodarczy Krajowego Rejestru Sądowego pod numerem KRS: 0001063030. Numer krajowy ZASI: PLZASI00360 Kapitał zakładowy: 46.000 zł NIP: 5242986705 REGON: 526662538 Dane kontaktowe</p>'
email: KDshares@verestro.com

portfolio: W trakcie przygotowania
