title: KD Shares
remote_theme: "verinvest-pl/WhatATheme"
heroimage: /assets/img/hero.jpg
description: Investing in Fintech Innovation for a Brighter Financial Future.

about: KD Shares ASI sp. z o.o. jest wewnętrznie zarządzaną alternatywną spółką inwestycyjną utworzoną na podstawie ustawy o funduszach inwestycyjnych i zarządzaniu alternatywnymi funduszami inwestycyjnymi. Spółka wpisana jest do rejestru zarządzających alternatywnymi spółkami inwestycyjnymi prowadzonego przez Komisję Nadzoru Finansowego pod numerem PLZASI00360. Wyłącznym przedmiotem działalności ASI jest zbieranie aktywów od wielu inwestorów, w celu ich lokowania w interesie tych inwestorów. Celem inwestycyjnym ASI jest zwiększanie wartości jej aktywów poprzez wzrost łącznej wartości lokat oraz uzyskanie odsetek z lokat i innych przychodów z lokat. Cel inwestycyjny realizowany jest zgodnie z przyjętą polityką i strategią inwestycyjną. ASI nie gwarantuje osiągnięcia celów inwestycyjnych. KD Shares ASI sp. z o.o. jako zarządzający ASI podlega nadzorowi Komisji Nadzoru Finansowego, która monitoruje wielkość aktywów ASI oraz kategorii lokat i rynków, na których inwestuje, w celu identyfikacji potencjalnych ryzyk systemowych, generowanych przez ogół zarządzających ASI.

authors:
  - image: https://verestro.com/uploads/media/images/0001/01/xthumb_178_images_small.jpeg.pagespeed.ic.3eH7J3nXbm.webp
    name: Krzysztof Drzyzga
    about: 'Krzysztof Drzyzga - Ponad 20 lat doświadczenia: w branży finansowej, płatności zdalne i zbliżeniowe, programy lojalnościowe, zarządzanie produktami, wspieranie rozwoju branży fintech, startupów i zarządzanie produktami. Odpowiedzialny za ogólną strategię i rozwój Verestro.'
  - image: /assets/img/kasia.jpg
    name: Katarzyna Drzyzga
    about: 'Katarzyna Drzyzga - Z branżą płatniczą i fintech związana od 15 lat. Odpowiedzialna za dział HR w Verestro. '

address: '<b>KD Shares ASI spółka z ograniczoną odpowiedzialnością</b>, ul.Promienna 10, 03-672 Warszawa <p>Spółka wpisana jest do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejestrowy dla m.st. Warszawy w Warszawie, XIV Wydział Gospodarczy Krajowego Rejestru Sądowego pod numerem KRS: 0001063030. Numer krajowy ZASI: PLZASI00360 Kapitał zakładowy: 46.000 zł NIP: 5242986705 REGON: 526662538 Dane kontaktowe</p>'
email: KDshares@verestro.com

portfolio: W trakcie przygotowania
