title: KD Shares
remote_theme: "verinvest-pl/WhatATheme"
heroimage: /assets/img/hero.jpg
description: Investing in Fintech Innovation for a Brighter Financial Future.

about: KD Shares jest alternatywnym funduszem inwestycyjnym założonym w celu zwiększania wartości inwestycji rodzinnych. KD Shares ASI działa zgodnie ze strategią inwestycyjną i koncentruje się na inwestycjach w spółki z obszaru fintech, digital oraz nowej gospodarki. 

authors:
  - image: https://verestro.com/uploads/media/images/0001/01/xthumb_178_images_small.jpeg.pagespeed.ic.3eH7J3nXbm.webp
    name: Krzysztof Drzyzga
    about: 'Krzysztof Drzyzga - Ponad 20 lat doświadczenia: w branży finansowej, płatności zdalne i zbliżeniowe, programy lojalnościowe, zarządzanie produktami, wspieranie rozwoju branży fintech, startupów i zarządzanie produktami. Odpowiedzialny za ogólną strategię i rozwój Verestro.'
  - image: /assets/img/kasia.jpg
    name: Katarzyna Drzyzga
    about: 'Katarzyna Drzyzga - Z branżą płatniczą i fintech związana od 15 lat. Odpowiedzialna za dział HR w Verestro.'

address: ul.Promienna 10, 03-672 Warszawa
email: KDshares@verestro.com

portfolio: W trakcie przygotowania
