title: KD Shares
remote_theme: "verinvest-pl/WhatATheme"
heroimage: /assets/img/hero.jpg
description: Investing in Fintech Innovation for a Brighter Financial Future.

author-about: KD Shares to zaawansowana alternatywna spółka inwestycyjna (ASI), która koncentruje się na wsparciu i rozwijaniu innowacyjnych rozwiązań fintech. Nasza misja polega na identyfikowaniu obiecujących projektów i startupów w obszarze finansów oraz inwestowaniu w nie, aby przyspieszyć ich rozwój. Dzięki naszemu doświadczeniu i wizji jesteśmy w stanie kształtować przyszłość finansów, wspierając technologie i innowacje, które mogą zmienić sposób, w jaki ludzie zarządzają swoimi finansami. W KD Shares wierzymy, że nasze inwestycje przynoszą korzyści zarówno naszym inwestorom, jak i całemu sektorowi fintech, tworząc innowacyjne rozwiązania, które mają potencjał rewolucjonizować branżę finansową.
author-image: /assets/img/avatar.jpg

authors:
  - image: https://verestro.com/uploads/media/images/0001/01/xthumb_178_images_small.jpeg.pagespeed.ic.3eH7J3nXbm.webp
    name: Krzysztof Drzyzga
    about: 'Krzysztof Drzyzga - Ponad 20 lat doświadczenia: w branży finansowej, płatności zdalne i zbliżeniowe, programy lojalnościowe, zarządzanie produktami, wspieranie rozwoju branży fintech, startupów i zarządzanie produktami. Odpowiedzialny za ogólną strategię i rozwój Verestro.'
  - image: /assets/img/kasia.jpg
    name: Katarzyna Drzyzga
    about: 'Katarzyna Drzyzga - Z branżą płatniczą i fintech związana od 15 lat. Odpowiedzialna za dział HR w Verestro.'

address: ul.Promienna 10, 03-672 Warszawa
email: KDshares@verestro.com

portfolio: W trakcie przygotowania