title: KD Shares
remote_theme: "verinvest-pl/WhatATheme"
heroimage: /assets/img/hero.jpg
description: Investing in Fintech Innovation for a Brighter Financial Future.

author-about: Verinvest to dynamiczna spółka inwestycyjna, która specjalizuje się w inwestowaniu w innowacyjne rozwiązania fintech. Nasza firma działa jako alternatywna spółka inwestycyjna (ASI) i jesteśmy dedykowani wspieraniu przyszłości finansów poprzez inwestycje w nowatorskie technologie i rozwiązania finansowe. Nasza misja to identyfikowanie, finansowanie i rozwijanie perspektywicznych startupów fintech, które mają potencjał zmienić sposób, w jaki ludzie zarządzają swoimi finansami. Dzięki naszej wiedzy eksperckiej i zaawansowanym strategiom inwestycyjnym jesteśmy w stanie przyczynić się do rozwoju przemysłu fintech i tworzenia wartości dla naszych inwestorów. Jesteśmy dumni z naszego zaangażowania w przyszłość finansów i dążenia do wspierania innowacyjnych przedsięwzięć w tym dynamicznym sektorze.
author-image: /assets/img/avatar.jpg

authors:
  - image: https://verestro.com/uploads/media/images/0001/01/xthumb_178_images_small.jpeg.pagespeed.ic.3eH7J3nXbm.webp
    name: Krzysztof Drzyzga
    about: 'Krzysztof Drzyzga - Ponad 20 lat doświadczenia: w branży finansowej, płatności zdalne i zbliżeniowe, programy lojalnościowe, zarządzanie produktami, wspieranie rozwoju branży fintech, startupów i zarządzanie produktami. Odpowiedzialny za ogólną strategię i rozwój Verestro.'
  - image: /assets/img/kasia.jpg
    name: Katarzyna Drzyzga
    about: 'Michał Maciąg - Z branżą płatniczą i fintech związany od 12 lat. Odpowiedzialny za dział IT i jego dynamiczny rozwój.'

address: ul.Promienna 10, 03-672 Warszawa
email: KDshares@verestro.com

portfolio: W trakcie przygotowania